import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AuthProvider } from "@descope/nextjs-sdk";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider
      projectId={
        process.env.NEXT_PUBLIC_DESCOPE_PROJECT_ID ||
        "P2dI567joFhavCcJGyGndtyHdFtF"
      }
    >
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </AuthProvider>
  );
}
